parameters:
- name: dockerRegistryServiceConnection
  default: ''
- name: dockerImage
  default: ''

jobs:  
- job: Scan
  displayName: Scan Docker Images
  steps:

  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'
      releaseType: 'stable'

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: ${{ parameters.dockerRegistryServiceConnection }}

  - script: |
      sudo apt-get install rpm
      wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
      sudo dpkg -i trivy_0.18.3_Linux-64bit.deb
      trivy -v

  - task: CmdLine@2
    displayName: Scan Docker Image using Trivy
    inputs:
      script: |
        trivy i ${{ parameters.dockerImage }}